service: sls-clean-template
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 256
  stage: ${opt:stage,'dev'}
  region: us-east-1
  environment:
    USER_TABLE_NAME: UsersTable-${self:provider.stage}
    STAGE: ${self:provider.stage}
    APP_ENVIRONMENT: ${self:provider.stage}
    SERVICE_NAME: ${self:service}
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
    DYNAMODB_LOCAL_ENDPOINT: http://localhost:8000
    AMAZON_REGION: ${self:provider.region}
    AMAZON_ACCOUNTID: '00000'
  iamRoleStatements:
    - ${file(infrastructure/iam/UsersTableIAM.yml):UsersTableIAM}

functions:
  - ${file(src/lambdas/endpoints/healthy.yml)}
  - ${file(src/lambdas/endpoints/user.yml)}

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

resources:
  Resources:
    UsersTable: ${file(infrastructure/resource/UsersTable.yml):UsersTable}

custom:
  UsersTable:
    name: !Ref UsersTable
    arn: !GetAtt UsersTable.Arn
  dynamodb:
    stages:
      - ${self:provider.stage}
    start: 
      host : localhost
      port: 8000
      migrate: true
      noStart: true
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      convertEmptyValues: true
  serverless-offline:
    httPort: 3000
    host: '127.0.0.1'
  resourceRoutes: true