UsersTable:
  Type: AWS::DynamoDB::Table
  DeletionPolicy: Retain
  Properties:
    TableName: UsersTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: userID
        AttributeType: S
    KeySchema:
      - AttributeName: userID
        KeyType: HASH